variables:
  major: 0
  minor: 1
  patch: $[counter('versioncounter_0_1', 0)]

name: $(major).$(minor).$(patch)

pool:
  vmImage: windows-latest

trigger: none

pr: none

steps:
- task: UseDotNet@2
  displayName: 'Use 6.0 .NET Runtime'
  inputs:
    packageType: "runtime"
    version: "6.0.x"

- task: UseDotNet@2
  displayName: 'Use 7.0 .NET Runtime'
  inputs:
    packageType: "runtime"
    version: "7.0.x"

- task: UseDotNet@2
  displayName: 'Use 8.0 .NET Runtime'
  inputs:
    packageType: "runtime"
    version: "8.0.x"

- task: UseDotNet@2
  displayName: 'Use latest .NET SDK'
  inputs:
    useGlobalJson: true

- script: |
    dotnet restore "src/Clara/Clara.csproj"
    dotnet restore "src/Clara.Analysis.LuceneNet/Clara.Analysis.LuceneNet.csproj"
    dotnet restore "src/Clara.Analysis.Morfologik/Clara.Analysis.Morfologik.csproj"
    dotnet restore "src/Clara.Analysis.Snowball/Clara.Analysis.Snowball.csproj"
    dotnet restore "src/Clara.Tests/Clara.Tests.csproj"
    dotnet build "src/Clara/Clara.csproj" --no-restore -c Release /p:Version=$(major).$(minor).$(patch)
    dotnet build "src/Clara.Analysis.LuceneNet/Clara.Analysis.LuceneNet.csproj" --no-restore -c Release /p:Version=$(major).$(minor).$(patch)
    dotnet build "src/Clara.Analysis.Morfologik/Clara.Analysis.Morfologik.csproj" --no-restore -c Release /p:Version=$(major).$(minor).$(patch)
    dotnet build "src/Clara.Analysis.Snowball/Clara.Analysis.Snowball.csproj" --no-restore -c Release /p:Version=$(major).$(minor).$(patch)
    dotnet build "src/Clara.Tests/Clara.Tests.csproj" --no-restore -c Release /p:Version=$(major).$(minor).$(patch)
  displayName: Restore and build projects

- script: |
    dotnet test "src/Clara.Tests/Clara.Tests.csproj" --no-build -c Release -l trx --results-directory $(Common.TestResultsDirectory) /p:Version=$(major).$(minor).$(patch)
  displayName: Run tests

- task: PublishTestResults@2
  inputs:
    searchFolder: "$(Common.TestResultsDirectory)"
    testRunner: VSTest
    testResultsFiles: "**/*.trx"
  condition: succeededOrFailed()
  displayName: Publish test results

- script: |
    dotnet pack "src/Clara/Clara.csproj" --no-build -c Release -o $(Build.ArtifactStagingDirectory) /p:Version=$(major).$(minor).$(patch)
    dotnet pack "src/Clara.Analysis.Morfologik/Clara.Analysis.Morfologik.csproj" --no-build -c Release -o $(Build.ArtifactStagingDirectory) /p:Version=$(major).$(minor).$(patch)
    dotnet pack "src/Clara.Analysis.Snowball/Clara.Analysis.Snowball.csproj" --no-build -c Release -o $(Build.ArtifactStagingDirectory) /p:Version=$(major).$(minor).$(patch)
  displayName: Pack project

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: "Clara"
  displayName: Push package
